# Generated by Django 6.0.5 on 2026-06-21 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('colegio', models.CharField(blank=True, default='', max_length=255)),
                ('grado_asignado', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('emoji', models.CharField(default='📌', max_length=10)),
                ('categorias', models.JSONField(default=list)),
                ('descripcion', models.TextField()),
                ('pasos_markdown', models.TextField(blank=True, default='')),
                ('tasa_eficacia', models.IntegerField(default=0)),
                ('etiqueta_eficacia', models.CharField(default='', max_length=100)),
                ('tiempo_setup', models.CharField(blank=True, default='', max_length=50)),
                ('contexto', models.CharField(blank=True, default='', max_length=100)),
                ('sugerida_por_ia', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'db_table': 'estrategia',
                'ordering': ['-tasa_eficacia'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('grado', models.CharField(max_length=100)),
                ('tipo_tdah', models.CharField(choices=[('Combinado', 'Combinado'), ('Inatento', 'Inatento'), ('Hiperactivo', 'Hiperactivo')], max_length=20)),
                ('fortalezas', models.JSONField(default=list)),
                ('atencion_promedio', models.IntegerField(default=0)),
                ('puntaje_participacion', models.IntegerField(default=0)),
                ('profesor', models.ForeignKey(blank=True, db_column='profesor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='EntradaBitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Alta agitacion', 'Alta agitación'), ('Logro positivo', 'Logro positivo'), ('Ajuste de entorno', 'Ajuste de entorno')], max_length=20)),
                ('puntaje_atencion', models.IntegerField(default=0, help_text='Valor entre 0 y 100')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='entradas_bitacora', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'db_table': 'entrada_bitacora',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('patron', models.TextField()),
                ('sugerencia', models.TextField()),
                ('generado_en', models.DateTimeField(auto_now=True)),
                ('entradas_hash', models.CharField(max_length=64)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Análisis de Bitácora',
                'db_table': 'analisis_bitacora',
            },
        ),
        migrations.CreateModel(
            name='MaterialAdaptado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=100)),
                ('dificultad', models.CharField(choices=[('Basico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=15)),
                ('contenido_markdown', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, db_column='estudiante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Material Adaptado',
                'verbose_name_plural': 'Materiales Adaptados',
                'db_table': 'material_adaptado',
            },
        ),
    ]
