# Generated by Django 6.0.5 on 2026-06-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialadaptado',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to=settings.AUTH_USER_MODEL),
        ),
    ]
