# Generated by Django 6.0.5 on 2026-06-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analisisbitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estrategia',
            options={'ordering': ['-tasa_eficacia'], 'verbose_name': 'Estrategia', 'verbose_name_plural': 'Estrategias'},
        ),
        migrations.RenameField(
            model_name='estrategia',
            old_name='pasos',
            new_name='categorias',
        ),
        migrations.RemoveField(
            model_name='estrategia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='contexto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='emoji',
            field=models.CharField(default='📌', max_length=10),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='etiqueta_eficacia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='pasos_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='tiempo_setup',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
